FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

ENV DEBIAN_FRONTEND noninteractive

EXPOSE 8080

COPY /llm_model/requirements.txt .
RUN pip install -r requirements.txt

COPY /llm_model .

ENTRYPOINT ["python3","-m", "server"]
