
FIXED_CATEGORIES = [
        {'id': 0, 'name': 'cube', 'supercategory': ''},
        {'id': 1, 'name': 'box', 'supercategory': ''},
        {'id': 2, 'name': 'table', 'supercategory': ''},
        {'id': 3, 'name': 'chair', 'supercategory': ''},
        {'id': 4, 'name': 'person', 'supercategory': ''},
        {'id': 5, 'name': 'nightstand', 'supercategory': ''},
        {'id': 6, 'name': 'drawer', 'supercategory': ''},
        {'id': 7, 'name': 'handle', 'supercategory': ''},
        {'id': 8, 'name': 'sink', 'supercategory': ''},
        {'id': 9, 'name': 'cucumber', 'supercategory': ''},
        {'id': 10, 'name': 'potato', 'supercategory': ''},
        {'id': 11, 'name': 'chili pepper', 'supercategory': ''},
        {'id': 12, 'name': 'bell pepper', 'supercategory': ''},
        {'id': 13, 'name': 'corn', 'supercategory': ''},
        {'id': 14, 'name': 'eggplant', 'supercategory': ''},
        {'id': 15, 'name': 'carrot', 'supercategory': ''},
        {'id': 16, 'name': 'garlic', 'supercategory': ''},
        {'id': 17, 'name': 'tomato', 'supercategory': ''},
        {'id': 18, 'name': 'toy cat', 'supercategory': ''},
        {'id': 19, 'name': 'plates', 'supercategory': ''},
        {'id': 20, 'name': 'mug', 'supercategory': ''},
        {'id': 21, 'name': 'cup', 'supercategory': ''},
        {'id': 22, 'name': 'crocs', 'supercategory': ''},
        {'id': 23, 'name': 'slippers', 'supercategory': ''},
        {'id': 24, 'name': 'hat with earflaps', 'supercategory': ''},
        {'id': 25, 'name': 't-shirt', 'supercategory': ''},
        {'id': 26, 'name': 'hoodie', 'supercategory': ''},
        {'id': 27, 'name': 'towel', 'supercategory': ''},
        {'id': 28, 'name': 'socks', 'supercategory': ''},
        {'id': 29, 'name': 'hat', 'supercategory': ''},
        {'id': 30, 'name': 'chips', 'supercategory': ''},
        {'id': 31, 'name': 'snickers', 'supercategory': ''},
        {'id': 32, 'name': 'bottle', 'supercategory': ''},
        {'id': 33, 'name': 'cans', 'supercategory': ''},
        {'id': 34, 'name': 'plastic bags', 'supercategory': ''},
        {'id': 35, 'name': 'charging', 'supercategory': ''},
    ]
